### ISSUE TITLE
Idea: Give additional context on why a build failed

### ISSUE THREAD

**Issue by ChristianMurphy** [uPortal-Project/uportal-home#803]
Currently when a Travis CI build fails the only context it gives in the PR is the status :x: 
https://www.travisbuddy.com/ is a service that offers to add comments showing what tests failed during CI.
Maybe it could help ease the contributing process? Thoughts?

**Comment by apetro** [comment]
It's an idea. There are tradeoffs in how noisy to make PR threads. Ideally the :x: speaks for itself -- one clicks it to see a menu of checks that might have failed, and then clicks a `Details` button to go look at e.g. the raw console log of the Travis CI run, and lo, right there in the console log is the detail about what failed.

So, dunno. I suspect we need more engaging with the PR UI controls we've already got rather than more comments.

That said, I wouldn't :-1: trying this.

**Comment by ChristianMurphy** [comment]
Let's pass on this for now, we can revisit later if need be.
